# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import serial

ser = serial.Serial('/dev/ttyACM0')
ser.flushInput()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(563, 336)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.poutre = QtWidgets.QFrame(self.centralwidget)
        self.poutre.setGeometry(QtCore.QRect(100, 140, 331, 51))
        self.poutre.setAutoFillBackground(False)
        self.poutre.setLineWidth(10)
        self.poutre.setFrameShape(QtWidgets.QFrame.HLine)
        self.poutre.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.poutre.setObjectName("poutre")
        self.ball = QtWidgets.QLabel(self.centralwidget)
        #self.ball = QtWidgets.QLabel('round label', self)
        self.ball.setGeometry(QtCore.QRect(230, 120, 58, 16))
        self.ball.setAutoFillBackground(True)
        self.ball.setStyleSheet("background-color:blue;border: 3px solid blue;border-radius: 40px;")
        self.ball.setObjectName("ball")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 563, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ball.setText(_translate("MainWindow", "Ball"))
        ser_bytes = ser.readline()
       	distance = float(ser_bytes[0:len(ser_bytes)].decode("utf-8"))
        self.ball.setGeometry(QtCore.QRect(230+distance, 120, 58, 16))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
